-- P02 only. Safe for a fresh database and additive for an existing P02 v3 database.
CREATE TABLE IF NOT EXISTS public."TblP02Discussions" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  join_code varchar(4) NOT NULL,
  title text,
  status text NOT NULL DEFAULT 'open',
  teacher_token uuid NOT NULL DEFAULT gen_random_uuid(),
  active_question_id bigint,
  created_at timestamptz NOT NULL DEFAULT now(),
  closed_at timestamptz
);

CREATE TABLE IF NOT EXISTS public."TblP02Questions" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  discussion_id bigint NOT NULL REFERENCES public."TblP02Discussions"(id) ON DELETE CASCADE,
  question_text text NOT NULL,
  sort_order integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."TblP02Participants" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  discussion_id bigint NOT NULL REFERENCES public."TblP02Discussions"(id) ON DELETE CASCADE,
  nickname varchar(50) NOT NULL,
  participant_token uuid NOT NULL DEFAULT gen_random_uuid(),
  joined_at timestamptz NOT NULL DEFAULT now(),
  left_at timestamptz
);

CREATE TABLE IF NOT EXISTS public."TblP02Answers" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  discussion_id bigint NOT NULL REFERENCES public."TblP02Discussions"(id) ON DELETE CASCADE,
  question_id bigint NOT NULL REFERENCES public."TblP02Questions"(id) ON DELETE CASCADE,
  participant_id bigint NOT NULL REFERENCES public."TblP02Participants"(id) ON DELETE CASCADE,
  content text NOT NULL,
  submitted_at timestamptz NOT NULL DEFAULT now()
);

-- Add only P02 v4 columns that may be absent from the legacy v3 tables.
ALTER TABLE public."TblP02Discussions"
  ADD COLUMN IF NOT EXISTS title text,
  ADD COLUMN IF NOT EXISTS closed_at timestamptz;

ALTER TABLE public."TblP02Participants"
  ADD COLUMN IF NOT EXISTS participant_token uuid DEFAULT gen_random_uuid();

UPDATE public."TblP02Participants"
SET participant_token = gen_random_uuid()
WHERE participant_token IS NULL;

ALTER TABLE public."TblP02Participants"
  ALTER COLUMN participant_token SET DEFAULT gen_random_uuid(),
  ALTER COLUMN participant_token SET NOT NULL;

CREATE TABLE IF NOT EXISTS public."TblP02AffinityBoards" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  discussion_id bigint NOT NULL REFERENCES public."TblP02Discussions"(id) ON DELETE CASCADE,
  question_id bigint NOT NULL REFERENCES public."TblP02Questions"(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "UQ_P02_AffinityBoardQuestion" UNIQUE (question_id)
);

CREATE TABLE IF NOT EXISTS public."TblP02AffinityCategories" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  board_id bigint NOT NULL REFERENCES public."TblP02AffinityBoards"(id) ON DELETE CASCADE,
  name varchar(100) NOT NULL,
  sort_order integer NOT NULL,
  color_key smallint NOT NULL DEFAULT 0 CHECK (color_key BETWEEN 0 AND 5),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "UQ_P02_AffinityCategorySort" UNIQUE (board_id, sort_order)
);

CREATE TABLE IF NOT EXISTS public."TblP02AffinityPlacements" (
  board_id bigint NOT NULL REFERENCES public."TblP02AffinityBoards"(id) ON DELETE CASCADE,
  answer_id bigint NOT NULL REFERENCES public."TblP02Answers"(id) ON DELETE CASCADE,
  category_id bigint REFERENCES public."TblP02AffinityCategories"(id) ON DELETE SET NULL,
  sort_order integer NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (board_id, answer_id)
);
