ALTER TABLE public."TblP02Discussions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."TblP02Questions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."TblP02Participants" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."TblP02Answers" ENABLE ROW LEVEL SECURITY;
