-- No schema-wide, all-tables, default-privilege, or non-P02 statements are used.
REVOKE ALL ON TABLE public."TblP02Discussions" FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public."TblP02Questions" FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public."TblP02Participants" FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public."TblP02Answers" FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public."TblP02AffinityBoards" FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public."TblP02AffinityCategories" FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public."TblP02AffinityPlacements" FROM PUBLIC, anon, authenticated;

REVOKE EXECUTE ON FUNCTION public."P02_CreateDiscussion"() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public."P02_JoinDiscussion"(text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public."P02_ResumeDiscussion"(bigint, bigint, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public."P02_GetTeacherState"(bigint, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public."P02_GetQuestions"(bigint, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public."P02_AddQuestion"(bigint, text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public."P02_SetActiveQuestion"(bigint, text, bigint) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public."P02_CloseDiscussion"(bigint, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public."P02_GetStudentState"(bigint, bigint, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public."P02_SubmitAnswer"(bigint, bigint, bigint, text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public."P02_LeaveDiscussion"(bigint, bigint, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public."P02_GetQuestionAnswers"(bigint, bigint, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public."P02_GetAffinityBoard"(bigint, bigint, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public."P02_CreateAffinityCategory"(bigint, bigint, text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public."P02_RenameAffinityCategory"(bigint, bigint, text, bigint, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public."P02_DeleteAffinityCategory"(bigint, bigint, text, bigint) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public."P02_MoveAffinityAnswer"(bigint, bigint, text, bigint, bigint) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public."P02_CreateDiscussion"() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public."P02_JoinDiscussion"(text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public."P02_ResumeDiscussion"(bigint, bigint, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public."P02_GetTeacherState"(bigint, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public."P02_GetQuestions"(bigint, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public."P02_AddQuestion"(bigint, text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public."P02_SetActiveQuestion"(bigint, text, bigint) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public."P02_CloseDiscussion"(bigint, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public."P02_GetStudentState"(bigint, bigint, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public."P02_SubmitAnswer"(bigint, bigint, bigint, text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public."P02_LeaveDiscussion"(bigint, bigint, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public."P02_GetQuestionAnswers"(bigint, bigint, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public."P02_GetAffinityBoard"(bigint, bigint, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public."P02_CreateAffinityCategory"(bigint, bigint, text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public."P02_RenameAffinityCategory"(bigint, bigint, text, bigint, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public."P02_DeleteAffinityCategory"(bigint, bigint, text, bigint) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public."P02_MoveAffinityAnswer"(bigint, bigint, text, bigint, bigint) TO anon, authenticated;
